version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234Qwer
      - POSTGRES_DB=cmsdb
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    ports:
      - "5437:5432"
      
  server:
    container_name: cms_server
    volumes:
      - ./server:/app
      - ./server/static:/app/static

    env_file:
      - .env
    build: ./server
    ports:
      - "8005:8000"
    depends_on:
      - db


  nginx:
    build: ./nginx
    volumes:
      - ./server/static:/static
    ports:
      - "85:80"
    depends_on:
      - server

volumes:
  postgres_data:
