# Generated by Django 4.1.7 on 2023-05-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipments',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
