# Generated by Django 4.1.7 on 2023-06-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_medicalequipments_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cms.medicalequipments'),
        ),
    ]
