# Generated by Django 4.1.7 on 2023-06-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_medicalequipmentdetails_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='anios_operando',
            field=models.IntegerField(verbose_name='años operando'),
        ),
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='duenio',
            field=models.CharField(max_length=200, verbose_name='dueño'),
        ),
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='instalacion_fecha',
            field=models.DateField(verbose_name='fecha de instalación'),
        ),
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
    ]
