# Generated by Django 4.1.7 on 2023-05-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_menuitems_options_menuitems_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
