# Generated by Django 4.1.7 on 2023-05-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_menuitems_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={},
        ),
    ]
