# Generated by Django 4.1.7 on 2023-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_medicalequipments_no_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipments',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
