# Generated by Django 4.1.7 on 2023-05-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_menuitems_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'menu items',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'ordering': ('name',), 'verbose_name_plural': 'menu items'},
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
