# Generated by Django 4.1.7 on 2023-05-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_menuitem_alter_menuitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
