# Generated by Django 4.1.7 on 2023-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_medicalequipmentdetails_instalacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='proximo_mprev',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='ultimo_mprev',
            field=models.DateField(blank=True, null=True),
        ),
    ]
