# Generated by Django 4.1.7 on 2023-06-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_medicalequipmentdetails_proximo_mprev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
