# Generated by Django 4.1.7 on 2023-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_medicalequipmentdetails_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio'),
        ),
    ]
