# Generated by Django 4.1.7 on 2023-05-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_menusubitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuSubItem',
        ),
    ]
