# Generated by Django 4.1.7 on 2023-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_medicalequipmentdetails_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='anios_operando',
            field=models.IntegerField(blank=True, null=True, verbose_name='años operando'),
        ),
    ]
