# Generated by Django 4.1.7 on 2023-07-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_medicalequipmentdetails_anios_operando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='anios_operando',
            field=models.IntegerField(default=0, verbose_name='años operando'),
            preserve_default=False,
        ),
    ]
