# Generated by Django 4.1.7 on 2023-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_menusubitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubitem',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
