# Generated by Django 4.1.7 on 2023-07-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_medicalequipmentdetails_anios_operando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmentdetails',
            name='anios_operando',
            field=models.IntegerField(null=True, verbose_name='años operando'),
        ),
    ]
