# Generated by Django 4.1.7 on 2023-10-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
