# Generated by Django 4.1.7 on 2023-05-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_menusubitem2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20)),
                ('equipment_type', models.CharField(choices=[('ECG', 'Electrocardiograma'), ('BP', 'Monitor de presion sanguinea'), ('SP', 'Estetoscopio'), ('OT', 'Tanque de oxigeno')], max_length=4)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('calibration_date', models.DateField()),
                ('last_service_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
